{
 "title": "Tea API",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(service)" } },
   {
    "name": "uri",
    "label": "URI",
    "query": {
     "query": "label_values({exported_job=\"$application\"},http_route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$application latency for $uri",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$application\", http_route=\"$uri\"}[$__rate_interval])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(.99  , sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$application\", http_route=\"$uri\"}[$__rate_interval])))",
     "legendFormat": "tp99"
    },
    {
     "expr": "histogram_quantile(.95, sum by(le) (rate(http_server_duration_milliseconds_bucket{exported_job=\"$application\", http_route=\"$uri\"}[$__rate_interval])))",
     "legendFormat": "tp95"
    }
   ]
  },
  {
   "title": "$application throughput for $uri",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(http_status_code) (rate(http_server_duration_milliseconds_count{exported_job=\"$application\", http_route=\"$uri\"}[$__rate_interval]))",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "steeped tea",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(name, size) (rate(tea_make_total[$__rate_interval]))",
     "legendFormat": "{{size}} {{name}}"
    }
   ]
  }
 ]
}